# Generated by Django 3.2.6 on 2021-10-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdtSections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='main_section',
        ),
    ]
