# Generated by Django 3.2.6 on 2021-10-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdtSections', '0002_remove_section_main_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_image',
            field=models.FileField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, upload_to='static/images'),
        ),
    ]
